name = "flights"
main = "dist/worker.js"
compatibility_date = "2025-09-24"
observability = { enabled = true }

[[durable_objects.bindings]]
name = "FLIGHTS_DO"
class_name = "FlightDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FlightDO"]