name = "flights-dev"
main = "dist/worker.js"
compatibility_date = "2025-09-24"
observability = { enabled = true }

[[kv_namespaces]]
binding = "METADATA"
#61263aff35f94b97805907138f2a0e91

[[durable_objects.bindings]]
name = "FLIGHTS_DO"
class_name = "FlightDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FlightDO"]